### ISSUE TITLE
Hiding tabs in rMarkdown

### ISSUE THREAD

**Issue by abfleishman** [eriqande/rep-res-course#73]
Hi Eric,
a friend of mine asked me the following and I thought that you might know if it is possible:

Any idea on making the output less static and let you click a heading to hide all the associated R output, etc?
This is what I'm hoping for : http://www.dhtmlgoodies.com/scripts/show-hide-content-slide/show-hide-content-slide.html

-A

**Comment by eriqande** [comment]
Hey Abram!
Thanks for the message.  I don't know how to do that directly from within
markdown or R markdown.  It looks like there is some support
in Markdown (at least some flavors) for spoiler text:

http://meta.stackexchange.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers

But otherwise you might have to implement it via some bootstrap templates
or raw html.  But I'm not really sure of that at al!

See you tomorrow.

eric

**Comment by eriqande** [comment]
Hey Abram,
Here is another possible solution:

http://answers.squarespace.com/questions/16924/how-do-i-create-hideshow-text-on-a-page-like-you-see-with-faqs
